from .jpg_save_node import NODE_CLASS_MAPPINGS as JPG_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as JPG_DISPLAY_MAPPINGS
from .ImageTileSplitter import NODE_CLASS_MAPPINGS as TILE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TILE_DISPLAY_MAPPINGS
from .size_input import NODE_CLASS_MAPPINGS as SIZE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SIZE_DISPLAY_MAPPINGS
from .random_seed_node import NODE_CLASS_MAPPINGS as SEED_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SEED_DISPLAY_MAPPINGS
from .image_resizer import NODE_CLASS_MAPPINGS as RESIZE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RESIZE_DISPLAY_MAPPINGS
from .crop_data import NODE_CLASS_MAPPINGS as CROP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CROP_DISPLAY_MAPPINGS

# 合并所有映射
NODE_CLASS_MAPPINGS = {
    **JPG_MAPPINGS,
    **TILE_MAPPINGS,
    **SIZE_MAPPINGS,
    **SEED_MAPPINGS,
    **RESIZE_MAPPINGS,
    **CROP_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **JPG_DISPLAY_MAPPINGS,
    **TILE_DISPLAY_MAPPINGS,
    **SIZE_DISPLAY_MAPPINGS,
    **SEED_DISPLAY_MAPPINGS,
    **RESIZE_DISPLAY_MAPPINGS,
    **CROP_DISPLAY_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']